### ISSUE TITLE
Possible error with Year Date Format

### ISSUE THREAD

**Issue by AlexPagnotta** [mazen160/whatsapp-chat-parser#1]
Hi, 

I'm using your library, working great, but I've had little error with the date format.
In my chat file the format for the date is `'[%d/%m/%y, %H:%M:%S]'` while in your code is expecting `'[%d/%m/%Y, %H:%M:%S]'`, with the long year.
Not sure if it's a regional thing, or maybe whatsapp has changed the export format.

**Comment by mazen160** [comment]
Hi Alex! Great to hear! Glad that it's been helpful
I'm not sure to be honest, maybe we can set the time-format into a string or an optional argument to avoid the issue from happening. Can you please make a PR for it?

**Comment by AlexPagnotta** [comment]
I've added a pull request, with date format as an optional parameter.
It seems to work, but I'm not fluent with python, so let me know if there is any problem.

**Comment by mazen160** [comment]
Hi @AlexPagnotta!

Thanks for the updates and apologize for the late review!

Looking great to me! Merging it now :100:
